### PR TITLE
Added few more test (coverage: 96+%)

### LINKED ISSUE #22: Make sure correct exception is thrown when an emotionfile is not found
SimpleIDE bugged when emotionfile was not found, make sure correct exceptions are thrown when this is the case.

### LINKED ISSUE #28: Relationparser coverage check
-Checking for the coverage of the relation parser. If needed create more tests to test every new function

### PR DESCRIPTION
**Pull request by mspanoghe**
closes #28
closes #22

### CODE REVIEW

**Comment by mspanoghe** [comment]
closes #22

**Comment by RolfStarre** [comment]
mooi

**Comment by trensen** [comment]
@mspanoghe you should have the `closes #22` in the PR's description, it won't close the issue currently when merging this PR.

**Comment by mspanoghe** [comment]
@trensen Thanks. I will change it.

**Comment by berndkr** [comment]
goed

**Pull request merged**
