### PR TITLE
Added correct emotion predicate name.

### LINKED ISSUE #17: Update defined keywords
gam/2 -> emotion/2 keyword
- relation/3 keyword

### LINKED ISSUE #18: Emotion Query Validator
Update validator for emotion queries after adding new keywords 

relevant changes are in gamQuery branch
e9335415af68c0751d01b0cd46a478373e30b3be

### PR DESCRIPTION
**Pull request by jwooning**
closes: #17 
closes: #18

### CODE REVIEW

**Comment by jwooning** [comment]
possible predicates are:
- emotion/2: emotion(joy, 0.2), emotion(happy-for, 0.8)
- emotion/3: emotion(happy-for, 0.5, otheragent)

**Comment by RolfStarre** [comment]
Goed!

**Comment by berndkr** [comment]
Ziet er goed uit

**Comment by mspanoghe** [comment]
Nice!

**Pull request merged**
